/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CompressOptions {
  width?: number
  level?: number
  strip?: string
}

export declare function compressPng(buffer: Buffer, options?: CompressOptions | undefined | null): Promise<unknown>
